supportedArchitectures:
  os:
  - linux
  - win32
  - darwin
  cpu:
  - x64
  - arm64
  libc:
  - glibc
  - musl

plugins:
- path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  spec: "@yarnpkg/plugin-workspace-tools"
nodeLinker: node-modules
