image:
  repository: ${BACKSTAGE_IMAGE}
  tag: ${BACKSTAGE_IMAGE_TAG}

serviceAccount:
  name: backstage-sa
  azureClientId: ${BACKSTAGE_MI_CLIENT_ID}

env:
  BACKSTAGE_HOST: ${BACKSTAGE_HOST_PREFIX}.${INGRESS_IP}.sslip.io
  ARGOCD_URL: https://${ARGOCD_HOST_PREFIX}.${INGRESS_IP}.sslip.io
  GITHUB_ORG: ${GITHUB_ORG}
  GITHUB_TOKEN: ${BACKSTAGE_GITHUB_TOKEN}
  TECHDOCS_STORAGE_ACCOUNT: ${STORAGE_ACCOUNT}
  TECHDOCS_CONTAINER: ${TECHDOCS_CONTAINER}

  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: backstage

  BACKSTAGE_AUTH_MODE: ${BACKSTAGE_AUTH_MODE}

  techdocs:
  storageAccount: ${TECHDOCS_STORAGE_ACCOUNT}
  storageKey: ${TECHDOCS_STORAGE_KEY}
  container: ${TECHDOCS_CONTAINER}

