image:
  repository: ${BACKSTAGE_IMAGE}
  tag: ${BACKSTAGE_IMAGE_TAG}

serviceAccount:
  name: backstage-sa
  azureClientId: ${BACKSTAGE_MI_CLIENT_ID}

env:
  # URLs
  BACKSTAGE_HOST: ${BACKSTAGE_HOST_PREFIX}.${INGRESS_IP}.sslip.io
  ARGOCD_URL: https://${ARGOCD_HOST_PREFIX}.${INGRESS_IP}.sslip.io

  # GitHub integration
  GITHUB_ORG: ${GITHUB_ORG}
  GITHUB_TOKEN: ${BACKSTAGE_GITHUB_TOKEN}

  # TechDocs storage
  TECHDOCS_STORAGE_ACCOUNT: ${STORAGE_ACCOUNT}
  TECHDOCS_CONTAINER: ${TECHDOCS_CONTAINER}
  TECHDOCS_STORAGE_KEY: ${TECHDOCS_STORAGE_KEY}

  # Postgres DB
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

  # Backstage authentication mode
  BACKSTAGE_AUTH_MODE: ${BACKSTAGE_AUTH_MODE}

  # Optional: Azure OIDC secrets (used by app-config.yaml)
  AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
  AZURE_TENANT_ID: ${AZURE_TENANT_ID}
