apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-fastapi-service
  title: Python FastAPI Service (AKS + Argo CD)
  description: Golden-path Python service with GitOps deployment and TechDocs.
spec:
  owner: group:platform-team
  type: service

  parameters:
    - title: Service Details
      required: [ name, owner, devHost, prodHost ]
      properties:
        name:
          title: Service name
          type: string
          description: kebab-case (e.g. orders-api)
        owner:
          title: Owner group
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: [Group]
        system:
          title: System
          type: string
          default: platform
        devHost:
          title: Dev host
          type: string
        prodHost:
          title: Prod host
          type: string

  steps:
    - id: fetch
      name: Render service skeleton
      action: fetch:template
      input:
        url: https://github.com/${GITHUB_ORG}/${PLATFORM_REPO}/tree/main/templates/backstage/templates/python-fastapi-service/skeleton-service
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          githubOrg: ${GITHUB_ORG}
          acrName: ${ACR_NAME}
          techdocsContainer: ${TECHDOCS_CONTAINER}

    - id: publish
      name: Create GitHub repo
      action: publish:github
      input:
        repoUrl: github.com?owner=${GITHUB_ORG}&repo=${{ parameters.name }}
        defaultBranch: main
        repoVisibility: private

    - id: gitops
      name: Render GitOps manifests
      action: fetch:template
      input:
        url: https://github.com/${GITHUB_ORG}/${PLATFORM_REPO}/tree/main/templates/backstage/templates/python-fastapi-service/skeleton-gitops
        values:
          name: ${{ parameters.name }}
          devHost: ${{ parameters.devHost }}
          prodHost: ${{ parameters.prodHost }}
          githubOrg: ${GITHUB_ORG}

    - id: pr
      name: Open PR to env-gitops
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=${GITHUB_ORG}&repo=${GITOPS_REPO}
        branchName: add-${{ parameters.name }}
        title: "Add ${{ parameters.name }} (dev/prod)"
        description: "Generated by Backstage"
        sourcePath: .
        targetPath: apps

    - id: register
      name: Register in catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: catalog-info.yaml

  output:
    links:
      - title: Service repo
        url: ${{ steps.publish.output.remoteUrl }}
      - title: GitOps PR
        url: ${{ steps.pr.output.remoteUrl }}
