image:
  repository: ghcr.io/backstage/backstage
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  name: backstage-sa

env:
  BACKSTAGE_HOST: ${BACKSTAGE_HOST}
  ARGOCD_URL: ${ARGOCD_URL}

  GITHUB_ORG: ${GITHUB_ORG}
  PLATFORM_REPO: ${PLATFORM_REPO}
  GITHUB_TOKEN: ${GITHUB_TOKEN}

  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

  TECHDOCS_STORAGE_ACCOUNT: ${TECHDOCS_STORAGE_ACCOUNT}
  TECHDOCS_STORAGE_KEY: ${TECHDOCS_STORAGE_KEY}
  TECHDOCS_CONTAINER: ${TECHDOCS_CONTAINER}

  AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
  AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
  AZURE_TENANT_ID: ${AZURE_TENANT_ID}

  BACKEND_AUTH_SECRET: ${BACKEND_AUTH_SECRET}
